"""add users table

Revision ID: 160916e73ce9
Revises: 43b99eaf0111
Create Date: 2023-03-12 13:55:33.256805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160916e73ce9'
down_revision = '43b99eaf0111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hashed', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
