"""add current price to stocks table

Revision ID: fec1b856a45f
Revises: e39ca394d463
Create Date: 2023-03-21 22:29:03.999545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec1b856a45f'
down_revision = 'e39ca394d463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_price_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('position_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('position_value')
        batch_op.drop_column('current_price_date')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
